### ISSUE TITLE
TEGYE LE

### ISSUE THREAD

**Issue by ddaniel-bit** [Hegedus-Gergo/gondok#3]
GYERE TEDD A SZÁMBA

**Comment by ddaniel-bit** [comment]
A LÉGIÓBAN NEM ILYEN SPRÉKET ÉLTEM ÁT

**Comment by Hegedus-Gergo** [comment]
6 12 tagállomáshoz gyertek azonnal, Busák József nem bír magábal, két karddal itt fenyegetőzik
